### PR TITLE
improve kombu types

### PR DESCRIPTION
**Pull request by peteris-zealid**

### CODE REVIEW

**Comment by sbdchd** [comment]
Thanks! it looks like black wants the files to be formatted, also I think pyright will want the default values to be `...` since this is a stub file

**Comment by peteris-zealid** [comment]
Sure, I see the pipe is failing - will fix. Did not find any contribution guidelines, so I just assumed that I can do whatever.

**Review by sbdchd — APPROVED** [review]

**Comment by sbdchd** [comment]
Thanks!

**Comment by peteris-zealid** [comment]
No, problem

**Pull request merged**
