### PR TITLE
add definition for utils.time.get_exponential_backoff_interval

### PR DESCRIPTION
**Pull request by joeyorlando**
[function definition](https://github.com/celery/celery/blob/c3063fc4cbb1c60cc451dda1843167ead0441d54/celery/utils/time.py#L415-L420) in the source

### CODE REVIEW

**Review by sbdchd — APPROVED** [review]

**Comment by sbdchd** [comment]
Looks good to me, thank you!

**Comment by sbdchd** [comment]
Ah linters are angry:

```
Run ./s/lint
[8](https://github.com/sbdchd/celery-types/actions/runs/5247139870/jobs/9483967933?pr=124#step:11:9)
+ [[ -n true ]]
[9](https://github.com/sbdchd/celery-types/actions/runs/5247139870/jobs/9483967933?pr=124#step:11:10)
+ ./.venv/bin/black --check .
[10](https://github.com/sbdchd/celery-types/actions/runs/5247139870/jobs/9483967933?pr=124#step:11:11)
All done! ✨ 🍰 ✨
[11](https://github.com/sbdchd/celery-types/actions/runs/5247139870/jobs/9483967933?pr=124#step:11:12)
145 files would be left unchanged.
[12](https://github.com/sbdchd/celery-types/actions/runs/5247139870/jobs/9483967933?pr=124#step:11:13)
+ ./.venv/bin/ruff .
[13](https://github.com/sbdchd/celery-types/actions/runs/5247139870/jobs/9483967933?pr=124#step:11:14)
celery-stubs/utils/time.pyi:9:18: UP007 [*] Use `X | Y` for type annotations
[14](https://github.com/sbdchd/celery-types/actions/runs/5247139870/jobs/9483967933?pr=124#step:11:15)
Found 1 error.
[15](https://github.com/sbdchd/celery-types/actions/runs/5247139870/jobs/9483967933?pr=124#step:11:16)
[*] 1 potentially fixable with the --fix option.
```

**Comment by joeyorlando** [comment]
fixed the linting errors + added some documentation on initial setup to be able to run `s/lint` locally. @sbdchd do you mind having another look? it looks like:

> This workflow requires approval from a maintainer.

**Comment by joeyorlando** [comment]
@sbdchd would it be possible for you to retrigger the build and merge if all is passing? 😄 

how're releases performed?

**Comment by sbdchd** [comment]
releases are still manual on my part, haven't gotten around to automating it yet 😬

**Pull request merged**
